<?php
    $this->headTitle()->append('Lançamentos');
    if ($this->type == 'add') :
        $this->headTitle()->append('Adicionar');
    endif;
    if ($this->type == 'edit') :
        $this->headTitle()->append('Editar');
    endif;
?>
<?php
    echo $this->partial('layout/page-header', array(
        'title'    => 'Lançamentos',
        'subtitle' => ($this->type == 'add' ? 'Adicionar' : 'Editar'),
    ))
?>

