<?php
    // Linguagem
    $language = strtolower(str_replace('_', '-', locale_get_default()));
    // Dependências
    $this->headLink()
        ->appendStylesheet($this->basePath('/assets/jQuery-Timepicker-Addon/dist/jquery-ui-timepicker-addon.min.css'));
    // Adicionar Javascript
    $this->headScript()
        ->appendFile($this->basePath('/assets/jQuery-Timepicker-Addon/dist/jquery-ui-timepicker-addon.min.js'))
        ->appendFile($this->basePath('/module/Balance/assets/jQuery-Timepicker-Addon/js/jquery-ui-timepicker-addon.js'))
        ->appendFile($this->basePath('/assets/numeral/min/numeral.min.js'))
        ->appendFile($this->basePath('/assets/numeral/min/languages/' . $language . '.min.js'))
        ->appendFile($this->basePath('/module/Balance/assets/default/js/postings-edit.js'));
    // Editar
    $this->headTitle()->append('Lançamentos');
    if ($this->type == 'add') :
        $this->headTitle()->append('Adicionar');
    endif;
    if ($this->type == 'edit') :
        $this->headTitle()->append('Editar');
    endif;
?>
<?php
    echo $this->partial('layout/page-header', [
        'title'    => 'Lançamentos',
        'subtitle' => ($this->type == 'add' ? 'Adicionar' : 'Editar'),
    ])
?>
<?php $this->form->get('entries')->setShouldCreateTemplate(true) ?>
<?php $this->form->prepare() ?>
<?php echo $this->form(null, null)->openTag($this->form) ?>

    <div class="balance-toolbar">
        <div class="btn-group" role="group">
            <button type="submit" class="btn btn-primary">Salvar</button>
            <a class="btn btn-warning" href="<?php echo $this->url('postings') ?>">Cancelar</a>
        </div><!-- btn-group -->
        <div class="btn-group" role="group">
            <button id="entries-add" type="button" class="btn btn-default">Adicionar Entrada</button>
        </div><!-- btn-group -->
    </div><!-- balance-toolbar -->

    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-title">Informações Básicas</div>
        </div><!-- panel-heading -->
        <div class="panel-body">
            <?php echo $this->formHidden($this->form->get('id')) ?>
            <div class="row">
                <div class="col-md-2">
                    <?php
                        $element = $this->form->get('datetime');
                        $element->setLabel('Data e Hora');
                        echo $this->formRow($element);
                    ?>
                </div><!-- col -->
            </div><!-- row -->
            <div class="row">
                <div class="col-md-12">
                    <?php
                        $element = $this->form->get('description');
                        $element->setLabel('Descrição');
                        echo $this->formRow($element);
                    ?>
                </div><!-- col -->
            </div><!-- row -->
        </div><!-- panel-body -->
    </div><!-- panel -->

    <?php echo $this->beforeEntries ?>

    <div id="entries" class="collection">
        <?php $element = $this->form->get('entries') ?>
        <div class="row collection-container">
            <?php foreach ($element as $subform) : ?>
                <div class="col-md-12 collection-element">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="btn-group pull-right">
                                <button type="button" class="btn btn-default btn-sm collection-element-move">
                                    <span class="glyphicon glyphicon-resize-vertical"></span>
                                </button>
                                <button type="button" class="btn btn-default btn-sm collection-element-remove">
                                    <span class="glyphicon glyphicon-remove"></span>
                                </button>
                            </div>
                            <div class="panel-title">Entrada</div>
                        </div><!-- panel-heading -->
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-3">
                                    <?php
                                        $subelement = $subform->get('type');
                                        $subelement->setLabel('Tipo');
                                        echo $this->formRow($subelement);
                                    ?>
                                </div><!-- col -->
                                <div class="col-md-3">
                                    <?php
                                        $subelement = $subform->get('account_id');
                                        $subelement->setLabel('Conta');
                                        echo $this->formRow($subelement);
                                    ?>
                                </div><!-- col -->
                                <div class="col-md-6">
                                    <?php
                                        $subelement = $subform->get('value');
                                        $subelement->setLabel('Valor');
                                        echo $this->formRow($subelement);
                                    ?>
                                </div><!-- col -->
                            </div><!-- row -->
                        </div><!-- panel-body -->
                    </div><!-- panel -->
                </div><!-- col -->
            <?php endforeach ?>
        </div><!-- collection-container -->

        <?php $this->placeholder('subform')->captureStart() ?>
            <?php $subform = $element->getTemplateElement() ?>
            <div class="col-md-12 collection-element">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="btn-group pull-right">
                            <button type="button" class="btn btn-default btn-sm collection-element-move">
                                <span class="glyphicon glyphicon-resize-vertical"></span>
                            </button>
                            <button type="button" class="btn btn-default btn-sm collection-element-remove">
                                <span class="glyphicon glyphicon-remove"></span>
                            </button>
                        </div>
                        <div class="panel-title">Entrada</div>
                    </div><!-- panel-heading -->
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-3">
                                <?php
                                    $subelement = $subform->get('type');
                                    $subelement->setLabel('Tipo');
                                    echo $this->formRow($subelement);
                                ?>
                            </div><!-- col -->
                            <div class="col-md-3">
                                <?php
                                    $subelement = $subform->get('account_id');
                                    $subelement->setLabel('Conta');
                                    echo $this->formRow($subelement);
                                ?>
                            </div><!-- col -->
                            <div class="col-md-6">
                                <?php
                                    $subelement = $subform->get('value');
                                    $subelement->setLabel('Valor');
                                    echo $this->formRow($subelement);
                                ?>
                            </div><!-- col -->
                        </div><!-- row -->
                    </div><!-- panel-body -->
                </div><!-- panel -->
            </div><!-- col -->
        <?php $this->placeholder('subform')->captureEnd() ?>
        <span class="collection-template" data-content="<?php echo $this->escapeHtml($this->placeholder('subform')) ?>" data-placeholder="<?php echo $element->getTemplatePlaceholder() ?>" data-count="<?php echo $element->getCount() ?>"></span>

    </div><!-- container-entries -->

<?php echo $this->form()->closeTag() ?>
