<?php
    // Dependências
    use Balance\Stdlib\Hydrator\Strategy as HydratorStrategy;
    use Balance\View\Table\Table;
    use Zend\Stdlib\Hydrator;

    // Dependências
    $this->headLink()
        ->appendStylesheet($this->basePath('/assets/jQuery-Timepicker-Addon/dist/jquery-ui-timepicker-addon.min.css'));
    // Dependências
    $this->headScript()
        ->appendFile($this->basePath('/assets/jQuery-Timepicker-Addon/dist/jquery-ui-timepicker-addon.min.js'))
        ->appendFile($this->basePath('/module/Balance/assets/jQuery-Timepicker-Addon/js/jquery-ui-timepicker-addon.js'));

    // Título
    $this->headTitle()
        ->append('Lançamentos')
        ->append('Listar');

    // I18n
    $datetime = $this->getHelperPluginManager()->getServiceLocator()->get('Balance\Stdlib\Hydrator\Strategy\Datetime');

    // Hidratação das Linhas
    $hydrator = (new Hydrator\ArraySerializable())
        ->addStrategy('datetime', $datetime);

    // Tabela
    $table = (new Table())
        ->setForm($form)
        ->setTitle('Listar Lançamentos')
        ->setColumn('datetime', ['label' => 'Data e Hora', 'class' => 'col-md-2'])
        ->setColumn('description', ['label' => 'Descrição', 'class' => 'col-md-8'])
        ->setElements($this->elements)
        ->setHydrator($hydrator);
    // Ação: Adicionar
    $table->setAction('add', ['route' => 'postings/add']);
    // Ação: Elemento - Editar
    $table->setElementAction('edit', ['route' => 'postings/edit']);
    // Ação: Elemento - Remover
    $table->setElementAction('remove', ['route' => 'postings/remove']);
    // Cabeçalho
    echo $this->partial('layout/page-header', [
        'title'    => 'Lançamentos',
        'subtitle' => 'Listar',
    ]);
    // Renderização
    echo $this->partial('layout/table', ['table' => $table, 'params' => $params]);
