<div class="row">
    <div class="col-md-12">
        <div id="alert-container">
            <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success', 'alert-dismissible')) ?>
            <?php echo $this->flashMessenger()->render('info',    array('alert', 'alert-info',    'alert-dismissible')) ?>
            <?php echo $this->flashMessenger()->render('warning', array('alert', 'alert-warning', 'alert-dismissible')) ?>
            <?php echo $this->flashMessenger()->render('error',   array('alert', 'alert-danger',  'alert-dismissible')) ?>
        </div>
    </div>
</div>
