<?php
    // Navigation
    $navigation = $this->navigation('navigation');
    // FlashMessenger
    $flashMessengerOpenContent  = '<div%s role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>';
    $flashMessengerCloseContent = '</div>';
    $this->flashMessenger()
        ->setMessageOpenFormat($flashMessengerOpenContent)
        ->setMessageSeparatorString($flashMessengerCloseContent . $flashMessengerOpenContent)
        ->setMessageCloseString($flashMessengerCloseContent);
?>
<?php echo $this->doctype('HTML5') ?>
<html lang="pt-br">
    <head>
        <?php
            $this->headMeta()
                ->setCharset('UTF-8')
                ->appendName('viewport', 'width=device-width, initial-scale=1');
            echo $this->headMeta();
        ?>
        <?php
            $this->headTitle()
                ->setSeparator(' - ')
                ->append('Balance');
            echo $this->headTitle();
        ?>
        <?php
            $this->headLink()
                ->headLink(array('rel' => 'shortcut icon', 'href' => $this->basePath('/images/favicon.ico'), 'type' => 'image/x-icon'))
                ->appendStylesheet($this->basePath('/assets/bootstrap/dist/css/bootstrap.min.css'))
                ->appendStylesheet($this->basePath('/assets/bootstrap/dist/css/bootstrap-theme.min.css'))
                ->appendStylesheet($this->basePath('/module/Balance/assets/default/css/default.css'));
            echo $this->headLink();
        ?>
        <?php
            $this->headScript()
                ->appendFile($this->basePath('/assets/jquery/dist/jquery.min.js'))
                ->appendFile($this->basePath('/assets/bootstrap/dist/js/bootstrap.min.js'));
            echo $this->headScript();
        ?>
    </head>
    <body>
        <?php echo $navigation->menu()->setPartial('layout/navigation') ?>
        <div class="container-fluid">
            <?php echo $navigation->breadcrumbs()->setPartial('layout/breadcrumbs') ?>
            <div class="row">
                <div class="col-md-12">
                    <div id="alert-container">
                        <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success', 'alert-dismissible')) ?>
                        <?php echo $this->flashMessenger()->render('info',    array('alert', 'alert-info',    'alert-dismissible')) ?>
                        <?php echo $this->flashMessenger()->render('warning', array('alert', 'alert-warning', 'alert-dismissible')) ?>
                        <?php echo $this->flashMessenger()->render('danger',  array('alert', 'alert-danger',  'alert-dismissible')) ?>
                    </div>
                </div>
            </div>
            <?php echo $this->content ?>
        </div>
    </body>
</html>
