<?php
    // Captura da Raiz
    $root = $this->navigation()->findOneByLabel('Balance');
    // Configuração de Classe
    $root->setClass('navbar-brand');
?>
<nav class="nav navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu" aria-expanded="false">
                <span class="sr-only">Alternar Navegação</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <?php echo $this->navigation()->menu()->htmlify($root) ?>
        </div>
        <div class="collapse navbar-collapse" id="menu">
            <ul class="nav navbar-nav">
                <?php foreach ($root as $page) : ?>
                    <?php if ($subpages = $page->findAllByVisible(true)) : ?>
                        <li class="dropdown">
                            <a href="<?php echo $page->getHref() ?>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <?php echo $page->getLabel() ?> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <?php foreach ($subpages as $subpage) : ?>
                                    <li>
                                        <?php echo $this->navigation()->menu()->htmlify($subpage) ?>
                                    </li>
                                <?php endforeach ?>
                            </ul>
                        </li>
                    <?php else : ?>
                        <li>
                            <?php echo $this->navigation()->menu()->htmlify($page) ?>
                        </li>
                    <?php endif ?>
                <?php endforeach ?>
            </ul>
        </div>
    </div>
</nav>
