<div class="row">
    <div class="col-md-12">
        <div class="text-right">
            <nav>
                <ul class="pagination">
                    <li class="<?php echo ($this->current == $this->first ? 'disabled' : '') ?>">
                        <a href="<?php echo $this->url($this->route, [], ['query' => array_merge($this->params, ['page' => $this->first])]) ?>"><span class="glyphicon glyphicon-fast-backward"></span></a>
                    </li>
                    <li class="<?php echo ($this->current == $this->first ? 'disabled' : '') ?>">
                        <a href="<?php echo $this->url($this->route, [], ['query' => array_merge($this->params, ['page' => $this->previous])]) ?>"><span class="glyphicon glyphicon-step-backward"></span></a>
                    </li>
                    <?php foreach ($this->pagesInRange as $page) : ?>
                        <li class="<?php echo ($this->current == $page ? 'active' : '') ?>">
                            <a href="<?php echo $this->url($this->route, [], ['query' => array_merge($this->params, ['page' => $page])]) ?>"><?php echo $this->escapeHtml($page) ?></a>
                        </li>
                    <?php endforeach ?>
                    <li class="<?php echo ($this->current == $this->last ? 'disabled' : '') ?>">
                        <a href="<?php echo $this->url($this->route, [], ['query' => array_merge($this->params, ['page' => $this->next])]) ?>"><span class="glyphicon glyphicon-step-forward"></span></a>
                    </li>
                    <li class="<?php echo ($this->current == $this->last ? 'disabled' : '') ?>">
                        <a href="<?php echo $this->url($this->route, [], ['query' => array_merge($this->params, ['page' => $this->last])]) ?>"><span class="glyphicon glyphicon-fast-forward"></span></a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>
