<?php if ($this->identifier == 'edit') : ?>
    <a class="btn btn-primary" href="<?php echo $this->url($this->params['route'], array('id' => $this->element['id'])) ?>" title="Editar Elemento">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        <span class="sr-only">Editar</span>
    </a>
<?php elseif ($this->identifier == 'remove') : ?>
    <a class="btn btn-danger" href="<?php echo $this->url($this->params['route'], array('id' => $this->element['id'])) ?>" title="Remover Elemento">
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        <span class="sr-only">Remove</span>
    </a>
<?php endif ?>
