<?php if ($this->identifier == 'add') : ?>
    <a class="btn btn-primary" href="<?php echo $this->url($this->params['route']) ?>">
        Adicionar
    </a>
<?php elseif ($this->identifier == 'edit') : ?>
    <a class="btn btn-primary" href="<?php echo $this->url($this->params['route'], array('id' => $this->element['id'])) ?>" title="Editar Elemento">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        <span class="sr-only">Editar</span>
    </a>
<?php elseif ($this->identifier == 'remove') : ?>
    <a class="btn btn-danger" href="<?php echo $this->url($this->params['route'], array('id' => $this->element['id'])) ?>" title="Remover Elemento" data-confirm="Você deseja realmente remover este elemento?">
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        <span class="sr-only">Remove</span>
    </a>
<?php elseif ($this->identifier == 'move') : ?>
    <button type="button" class="btn btn-default table-move" data-id="<?php echo $this->escapeHtml($this->element['id']) ?>">
        <span class="glyphicon glyphicon-resize-vertical"></span>
    </button>
<?php endif ?>
