<?php
    // Inicialização
    $columns        = $this->table->getColumns();
    $elements       = $this->table->getElements();
    $actions        = $this->table->getActions();
    $elementActions = $this->table->getElementActions();
?>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="btn-group pull-right">
                    <?php foreach ($actions as $identifier => $params) : ?>
                        <?php echo $this->partial('layout/table-action', array('identifier' => $identifier, 'params' => $params)) ?>
                    <?php endforeach ?>
                </div>
                <div class="panel-title">
                    <?php echo $this->escapeHtml($this->table->getTitle()) ?>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <?php foreach ($columns as $column) : ?>
                            <th><?php echo $this->escapeHtml($column) ?></th>
                        <?php endforeach ?>
                        <th class="table-action-<?php echo count($elementActions) ?>">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (count($elements) > 0) : ?>
                        <?php foreach ($elements as $element) : ?>
                            <tr>
                                <?php foreach ($columns as $identifier => $column) : ?>
                                    <td><?php echo $this->escapeHtml($element[$identifier]) ?></td>
                                <?php endforeach ?>
                                <td>
                                    <?php foreach ($elementActions as $identifier => $params) : ?>
                                        <?php echo $this->partial('layout/table-action', array('identifier' => $identifier, 'element' => $element, 'params' => $params)) ?>
                                    <?php endforeach ?>
                                </td>
                            </tr>
                        <?php endforeach ?>
                    <?php endif ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
