<?php
    // Inicialização
    $columns  = $this->table->getColumns();
    $elements = $this->table->getElements();
    $actions  = $this->table->getActions();
?>
<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <?php foreach ($columns as $column) : ?>
                            <th><?php echo $this->escapeHtml($column) ?></th>
                        <?php endforeach ?>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (count($elements) > 0) : ?>
                        <?php foreach ($elements as $element) : ?>
                            <tr>
                                <?php foreach ($columns as $identifier => $column) : ?>
                                    <td><?php echo $this->escapeHtml($element[$identifier]) ?></td>
                                <?php endforeach ?>
                                <td>
                                    <?php foreach ($actions as $identifier => $action) : ?>
                                        <?php echo call_user_func($action, $element) ?>
                                    <?php endforeach ?>
                                </td>
                            </tr>
                        <?php endforeach ?>
                    <?php endif ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
