<?php
    // Inicialização
    $form           = $this->table->getForm();
    $columns        = $this->table->getColumns();
    $elements       = $this->table->getElements();
    $actions        = $this->table->getActions();
    $elementActions = $this->table->getElementActions();
    $hydrator       = $this->table->getHydrator();
?>

<?php $form->prepare() ?>
<form class="form-inline" action="<?php echo $this->url() ?>" method="GET">
    <div class="balance-toolbar">
        <div class="btn-group">
            <?php foreach ($actions as $identifier => $params) : ?>
                <?php echo $this->partial('layout/table-action', array('identifier' => $identifier, 'params' => $params)) ?>
            <?php endforeach ?>
        </div><!-- btn-group -->
        <div class="btn-group">
            <a class="btn btn-warning" href="<?php echo $this->url() ?>">Limpar</a>
            <button type="submit" class="btn btn-default">Pesquisar</button>
        </div>
    </div><!-- balance-toolbar -->
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-title">
                Pesquisa
            </div><!-- panel-title -->
        </div><!-- panel-heading -->
        <div class="panel-body">
            <?php foreach ($form as $element) : ?>
                <?php echo $this->formRow($element) ?>
            <?php endforeach ?>
        </div><!-- panel-body -->
    </div><!-- panel -->
</form>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">
                    <?php echo $this->escapeHtml($this->table->getTitle()) ?>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <?php foreach ($columns as $column) : ?>
                            <th class="<?php echo (empty($column['class']) ? '' : $this->escapeHtml($column['class'])) ?>"><?php echo (empty($column['label']) ? '' : $this->escapeHtml($column['label'])) ?></th>
                        <?php endforeach ?>
                        <th class="col-md-2">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (count($elements) > 0) : ?>
                        <?php foreach ($elements as $element) : ?>
                            <?php if ($hydrator) : ?>
                                <?php $element = $hydrator->extract($element) ?>
                            <?php endif ?>
                            <tr>
                                <?php foreach ($columns as $identifier => $column) : ?>
                                    <td><?php echo $this->escapeHtml($element[$identifier]) ?></td>
                                <?php endforeach ?>
                                <td class="text-center">
                                    <?php foreach ($elementActions as $identifier => $params) : ?>
                                        <?php echo $this->partial('layout/table-action', array('identifier' => $identifier, 'element' => $element, 'params' => $params)) ?>
                                    <?php endforeach ?>
                                </td>
                            </tr>
                        <?php endforeach ?>
                    <?php else : ?>
                        <tr>
                            <td colspan="<?php echo (count($columns) + 1) ?>">
                                <div class="text-center">
                                    Nenhum Elemento Encontrado
                                </div>
                            </td>
                        </tr>
                    <?php endif ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php if ($elements instanceof Zend\Paginator\Paginator) : ?>
    <?php echo $this->paginationControl($elements, 'Sliding', 'layout/pagination') ?>
<?php endif ?>
