<?php
    $this->headTitle()->append('Contas');
    if ($this->type == 'add') :
        $this->headTitle()->append('Adicionar');
    endif;
    if ($this->type == 'edit') :
        $this->headTitle()->append('Editar');
    endif;
?>

<?php
    echo $this->partial('layout/page-header', array(
        'title'    => 'Contas',
        'subtitle' => ($this->type == 'add' ? 'Adicionar' : 'Editar'),
    ))
?>

<?php $this->form->prepare() ?>

<?php echo $this->form(null, null)->openTag($this->form) ?>

    <?php echo $this->formHidden($this->form->get('id')) ?>

    <div class="row">
        <div class="col-md-2">
            <?php
                $element = $this->form->get('type');
                $element
                    ->setLabel('Tipo')
                    ->setEmptyOption('-- Selecione --');
                echo $this->formRow($element);
            ?>
        </div>
        <div class="col-md-10">
            <?php
                $element = $this->form->get('name');
                $element
                    ->setLabel('Nome');
                echo $this->formRow($element);
            ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <?php
                $element = $this->form->get('description');
                $element
                    ->setLabel('Nome');
                echo $this->formRow($element);
            ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="text-right">
                <button class="btn btn-primary" type="submit">Salvar</button>
            </div>
        </div>
    </div>

<?php echo $this->form()->closeTag() ?>

