<?php
    // Dependências
    use Balance\View\Table;

    // Título
    $this->headTitle()
        ->append('Contas')
        ->append('Listar');

    // Tabela
    $table = (new Table\Table())
        ->addColumn('name', 'Nome')
        ->addColumn('type', 'Tipo')
        ->setElements($elements);
    // Ação: Editar
    $table->addAction('edit', array('route' => 'accounts/edit'));
    // Ação: Remover
    $table->addAction('remove', array('route' => 'accounts/remove'));
?>

<?php
    echo $this->partial('layout/page-header', array(
        'title'    => 'Contas',
        'subtitle' => 'Listar',
    ))
?>

<?php echo $this->partial('layout/table', array('table' => $table)) ?>
