<?php
    // Dependências
    use Balance\View\Table\Table;

    // Adicionar Javascript
    $this->headScript()
        ->appendFile($this->basePath('/module/Balance/assets/default/js/accounts-list.js'));

    // Título
    $this->headTitle()
        ->append('Contas')
        ->append('Listar');

    // Tabela
    $table = (new Table())
        ->setForm($form)
        ->setTitle('Listagem')
        ->setColumn('name', ['label' => 'Nome', 'class' => 'col-md-8'])
        ->setColumn('type', ['label' => 'Tipo', 'class' => 'col-md-2'])
        ->setElements($this->elements);
    // Ação: Adicionar
    $table->setAction('add', ['route' => 'accounts/add']);
    // Ação: Elemento - Mover
    $table->setElementAction('move');
    // Ação: Elemento - Editar
    $table->setElementAction('edit', ['route' => 'accounts/edit']);
    // Ação: Elemento - Remover
    $table->setElementAction('remove', ['route' => 'accounts/remove']);
    // Cabeçalho
    echo $this->partial('layout/page-header', [
        'title'    => 'Contas',
        'subtitle' => 'Listar',
    ]);
    // Renderização
    echo $this->partial('layout/table', ['table' => $table]);
