<?php
    // Dependências
    use Balance\View\Table\Table;

    // Adicionar Javascript
    $this->headScript()
        ->appendFile($this->basePath('/module/Balance/assets/default/js/accounts-list.js'));

    // Título
    $this->headTitle()
        ->append('Contas')
        ->append('Listar');

    // Tabela
    $table = (new Table())
        ->setForm($form)
        ->setTitle('Listagem')
        ->setColumn('name', array('label' => 'Nome', 'class' => 'col-md-8'))
        ->setColumn('type', array('label' => 'Tipo', 'class' => 'col-md-2'))
        ->setElements($this->elements);
    // Ação: Adicionar
    $table->setAction('add', array('route' => 'accounts/add'));
    // Ação: Elemento - Mover
    $table->setElementAction('move');
    // Ação: Elemento - Editar
    $table->setElementAction('edit', array('route' => 'accounts/edit'));
    // Ação: Elemento - Remover
    $table->setElementAction('remove', array('route' => 'accounts/remove'));
    // Cabeçalho
    echo $this->partial('layout/page-header', array(
        'title'    => 'Contas',
        'subtitle' => 'Listar',
    ));
    // Renderização
    echo $this->partial('layout/table', array('table' => $table));
