<?php
    // Título
    $this->headTitle()
        ->append('Configurações')
        ->append('Módulos');
    // Dependências
    $this->headScript()
        ->appendFile($this->basePath('/module/Balance/assets/default/js/configs-modules.js'));
    // Cabeçalho
    echo $this->partial('layout/page-header', [
        'title'    => 'Configurações',
        'subtitle' => 'Módulos',
    ]);
?>

<form id="form-modules" action="<?php echo $this->url() ?>" method="POST">
    <div class="row">

        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Módulo Padrão
                    <div class="pull-right">
                        <div class="checkbox">
                            <input type="checkbox" value="balance" checked disabled>
                        </div>
                    </div>
                </div><!-- panel-heading -->
                <div class="panel-body">
                    Este módulo representa todos os recursos básicos do Balance, incluindo o gerenciamento de contas e lançamentos, bem como o cálculo do balance na página principal do sistema.
                </div><!-- panel-body -->
            </div><!-- panel -->
        </div><!-- col -->

        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Relatórios
                    <div class="pull-right">
                        <div class="checkbox">
                            <input type="checkbox" value="balance-reports">
                        </div>
                    </div>
                </div><!-- panel-heading -->
                <div class="panel-body">
                    Módulo responsável pela apresentação de relatórios, utilizando os dados cadastrados no módulo básico do Balance. Informando uma conta na filtragem, podemos visualizar uma listagem com valores e tipos de entradas de lançamentos e sua descrição.
                </div><!-- panel-body -->
            </div><!-- panel -->
        </div><!-- col -->

        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Etiquetas
                    <div class="pull-right">
                        <div class="checkbox">
                            <input type="checkbox" value="balance-tags">
                        </div>
                    </div>
                </div><!-- panel-heading -->
                <div class="panel-body">
                    Etiquetas identificam e catalogam lançamentos. Estes poderão receber múltiplas etiquetas, representando assim a sua finalidade de lançamento. Com isto, podemos utilizar a consulta de lançamentos, filtrando as informações conforme as etiquetas utilizadas.
                </div><!-- panel-body -->
            </div><!-- panel -->
        </div><!-- col -->

    </div><!-- row -->
</form>
