<?php
    // Título
    $this->headTitle()
        ->append('Configurações')
        ->append('Módulos');
    // Dependências
    $this->headScript()
        ->appendFile($this->basePath('/module/Balance/assets/default/js/configs-modules.js'));
    // Cabeçalho
    echo $this->partial('layout/page-header', [
        'title'    => 'Configurações',
        'subtitle' => 'Módulos',
    ]);
?>

<form id="form-modules" action="<?php echo $this->url() ?>" method="POST">
    <div class="balance-toolbar">
        <div class="btn-group" role="group" aria-label="Ferramentas">
            <button type="submit" class="btn btn-primary">Salvar</button>
            <button type="button" class="btn btn-warning btn-reset">Cancelar</button>
        </div><!-- btn-group -->
    </div><!-- balance-toolbar -->

    <div class="row">
        <?php foreach ($modules as $module) : ?>
            <div class="col-md-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <?php echo $this->escapeHtml($module['title']) ?>
                        <div class="pull-right">
                            <div class="checkbox">
                                <input type="checkbox" value="balance" <?php echo $module['installed'] ? 'checked' : '' ?> <?php echo $module['core'] ? 'disabled' : '' ?>>
                            </div>
                        </div>
                    </div><!-- panel-heading -->
                    <div class="panel-body">
                        <?php echo $this->escapeHtml($module['description']) ?>
                    </div><!-- panel-body -->
                </div><!-- panel -->
            </div><!-- col -->
        <?php endforeach ?>
    </div><!-- row -->
</form>
