<?php
    // Título
    $this->headTitle()->append('Página Principal');
    // Dependências
    $this->headLink()
        ->appendStylesheet($this->basePath('/assets/jQuery-Timepicker-Addon/dist/jquery-ui-timepicker-addon.min.css'));
    // Dependências
    $this->headScript()
        ->appendFile($this->basePath('/assets/jQuery-Timepicker-Addon/dist/jquery-ui-timepicker-addon.min.js'))
        ->appendFile($this->basePath('/module/Balance/assets/jQuery-Timepicker-Addon/js/jquery-ui-timepicker-addon.js'));
?>
<?php
    echo $this->partial('layout/page-header', array(
        'title'    => 'Balance',
        'subtitle' => 'Balancete Completo',
    ));
?>
<?php $form->prepare() ?>
<form action="<?php echo $this->url() ?>" method="GET">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Pesquisa
                </div><!-- panel-heading -->
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-2">
                            <?php
                                $element = $form->get('datetime');
                                $element->setLabel('Data e Hora Limite');
                                echo $this->formRow($element);
                            ?>
                        </div>
                    </div>
                </div><!-- panel-body -->
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="text-right">
                                <button type="submit" class="btn btn-primary">Filtrar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- panel -->
        </div><!-- col -->
    </div><!-- row -->
</form>

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th class="col-md-2">Tipo</th>
                <th class="col-md-5">Conta</th>
                <th class="col-md-5">Valor</th>
            </tr>
        </thead>
        <tbody>
            <?php if (count($this->elements['ACTIVE'])) : ?>
                <?php $first = true ?>
                <?php foreach ($this->elements['ACTIVE'] as $account) : ?>
                    <tr>
                        <?php if ($first) : ?>
                            <td class="active" rowspan="<?php echo count($this->elements['ACTIVE']) ?>">Ativo</td>
                            <?php $first = false ?>
                        <?php endif ?>
                        <td class="<?php echo ($account['value'] < 0 ? 'danger' : 'success') ?>"><a href="<?php echo $this->url('postings/list') . '?account_id=' . $account['id'] ?>"><?php echo $this->escapeHtml($account['name']) ?></a></td>
                        <td class="<?php echo ($account['value'] < 0 ? 'danger' : 'success') ?>"><?php echo $this->escapeHtml($account['currency']) ?></td>
                    </tr>
                <?php endforeach ?>
            <?php else : ?>
                <tr>
                    <td>Ativo</td>
                    <td colspan="2">
                        <div class="text-center">Nenhum Elemento Encontrado</div>
                    </td>
                </tr>
            <?php endif ?>

            <?php if (count($this->elements['PASSIVE'])) : ?>
                <?php $first = true ?>
                <?php foreach ($this->elements['PASSIVE'] as $account) : ?>
                    <tr>
                        <?php if ($first) : ?>
                            <td class="active" rowspan="<?php echo count($this->elements['PASSIVE']) ?>">Passivo</td>
                            <?php $first = false ?>
                        <?php endif ?>
                        <td class="<?php echo ($account['value'] < 0 ? 'danger' : 'success') ?>"><a href="<?php echo $this->url('postings/list') . '?account_id=' . $account['id'] ?>"><?php echo $this->escapeHtml($account['name']) ?></a></td>
                        <td class="<?php echo ($account['value'] < 0 ? 'danger' : 'success') ?>"><?php echo $this->escapeHtml($account['currency']) ?></td>
                    </tr>
                <?php endforeach ?>
            <?php else : ?>
                <tr>
                    <td>Passivo</td>
                    <td colspan="2">
                        <div class="text-center">Nenhum Elemento Encontrado</div>
                    </td>
                </tr>
            <?php endif ?>
        </tbody>
        <tfoot>
            <tr>
                <th class="active" colspan="2"><?php echo $this->escapeHtml($this->elements['ACCUMULATE']['name']) ?></th>
                <th class="<?php echo ($this->elements['ACCUMULATE']['value'] < 0 ? 'danger' : 'success') ?>"><?php echo $this->escapeHtml($this->elements['ACCUMULATE']['currency']) ?></th>
            </tr>
        </tfoot>
    </table>
</div>
