<?php
    $this->headTitle()
        ->append('Página Principal');
?>

<?php
    echo $this->partial('layout/page-header', array(
        'title'    => 'Balance',
        'subtitle' => 'Balancete Completo',
    ));
?>

<div class="row">
    <div class="col-md-12">
        <form action="<?php echo $this->url('home') ?>" method="post">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Pesquisa
                </div><!-- panel-heading -->
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="datetime">Data e Hora Limite</label>
                                <input id="datetime" type="text" class="form-control">
                            </div>
                        </div>
                    </div>
                </div><!-- panel-body -->
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="text-right">
                                <button type="submit" class="btn btn-primary">Filtrar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- panel -->
        </form>
    </div><!-- col -->
</div><!-- row -->

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Tipo</th>
                <th>Conta</th>
                <th>Valor</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td rowspan="3">Ativo</td>
                <td>Poupança</td>
                <td>R$3000,00</td>
            </tr>
            <tr>
                <td>Banco</td>
                <td>R$1000,00</td>
            </tr>
            <tr>
                <td>Caixa</td>
                <td>R$500,00</td>
            </tr>
            <tr>
                <td rowspan="2">Passivo</td>
                <td>Capital</td>
                <td>R$6000,00</td>
            </tr>
            <tr>
                <td>Cartão de Crédito</td>
                <td>R$800,00</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <th>&nbsp;</th>
                <th>Lucro</th>
                <th>R$1200,00</th>
            </tr>
        </tfoot>
    </table>
</div>
