<?php
    $this->headTitle()
        ->append('Página Principal');
?>

<?php
    echo $this->partial('layout/page-header', array(
        'title'    => 'Balance',
        'subtitle' => 'Balancete Completo',
    ));
?>

<div class="row">
    <div class="col-md-12">
        <form action="<?php echo $this->url('home') ?>" method="post">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Pesquisa
                </div><!-- panel-heading -->
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-2">
                            <div class="form-group">
                                <label for="datetime">Data e Hora Limite</label>
                                <input id="datetime" type="text" class="form-control">
                            </div>
                        </div>
                    </div>
                </div><!-- panel-body -->
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="text-right">
                                <button type="submit" class="btn btn-primary">Filtrar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- panel -->
        </form>
    </div><!-- col -->
</div><!-- row -->

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Tipo</th>
                <th>Conta</th>
                <th>Valor</th>
            </tr>
        </thead>
        <tbody>
            <?php if (count($this->elements['ACTIVE'])) : ?>
                <?php $first = true ?>
                <?php foreach ($this->elements['ACTIVE'] as $account) : ?>
                    <tr>
                        <?php if ($first) : ?>
                            <td rowspan="<?php echo count($this->elements['ACTIVE']) ?>">Ativo</td>
                            <?php $first = false ?>
                        <?php endif ?>
                        <td><?php echo $this->escapeHtml($account['name']) ?></td>
                        <td><?php echo $this->escapeHtml($account['value']) ?></td>
                    </tr>
                <?php endforeach ?>
            <?php else : ?>
                <tr>
                    <td>Ativo</td>
                    <td colspan="2">
                        <div class="text-center">Nenhum Elemento Encontrado</div>
                    </td>
                </tr>
            <?php endif ?>

            <?php if (count($this->elements['PASSIVE'])) : ?>
                <?php $first = true ?>
                <?php foreach ($this->elements['PASSIVE'] as $account) : ?>
                    <tr>
                        <?php if ($first) : ?>
                            <td rowspan="<?php echo count($this->elements['PASSIVE']) ?>">Passivo</td>
                            <?php $first = false ?>
                        <?php endif ?>
                        <td><?php echo $this->escapeHtml($account['name']) ?></td>
                        <td><?php echo $this->escapeHtml($account['value']) ?></td>
                    </tr>
                <?php endforeach ?>
            <?php else : ?>
                <tr>
                    <td>Passivo</td>
                    <td colspan="2">
                        <div class="text-center">Nenhum Elemento Encontrado</div>
                    </td>
                </tr>
            <?php endif ?>
        </tbody>
        <tfoot>
            <tr>
                <th>&nbsp;</th>
                <th><?php echo $this->escapeHtml($this->elements['ACCUMULATE']['name']) ?></th>
                <th><?php echo $this->escapeHtml($this->elements['ACCUMULATE']['value']) ?></th>
            </tr>
        </tfoot>
    </table>
</div>
