<?php
    echo $this->partial('layout/page-header', [
        'title'    => 'Erro Encontrado',
        'subtitle' => 'Problema Interno',
    ]);
    // Título
    $this->headTitle()
        ->append('Erro Encontrado')
        ->append('Problema Interno');
?>

<p class="lead"><?php echo $this->escapeHtml($this->message) ?></p>

<?php if ($this->display_exceptions) : ?>
    <?php echo $this->partial('layout/exceptions', ['exception' => $this->exception]) ?>
<?php endif ?>
