<?php
    echo $this->partial('layout/page-header', array(
        'title'    => 'Erro Encontrado',
        'subtitle' => 'Problema Interno',
    ));
?>

<p class="lead"><?php echo $this->escapeHtml($this->message) ?></p>

<?php if ($this->display_exceptions) : ?>
    <?php $exception = $this->exception ?>
    <?php while ($exception) : ?>
        <hr>
        <dl>
            <dt>Class</dt>
            <dd><?php echo get_class($exception) ?></dd>
            <dt>File</dt>
            <dd><?php echo $exception->getFile() ?>:<?php echo $exception->getLine() ?></dd>
            <dt>Message</dt>
            <dd><?php echo $exception->getMessage() ?></dd>
            <dt>Code</dt>
            <dd><?php echo $exception->getCode() ?></dd>
            <dt>Stack Trace</dt>
            <dd>
                <pre><?php echo $this->escapeHtml($exception->getTraceAsString()) ?></pre>
            </dd>
        </dl>
        <?php $exception = $exception->getPrevious() ?>
    <?php endwhile ?>
<?php endif ?>
