<div class="page-header">
    <h1>Erro Encontrado <small>Problema Interno</small></h1>
</div>

<p class="lead"><?php echo $this->escapeHtml($this->message) ?></p>

<?php if ($this->display_exceptions) : ?>
    <dl>
        <dt>Class</dt>
        <dd><?php echo get_class($this->exception) ?></dd>
        <dt>File</dt>
        <dd><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></dd>
        <dt>Message</dt>
        <dd><?php echo $this->exception->getMessage() ?></dd>
        <dt>Code</dt>
        <dd><?php echo $this->exception->getCode() ?></dd>
        <dt>Stack Trace</dt>
        <dd>
            <pre><?php echo $this->escapeHtml($this->exception->getTraceAsString()) ?></pre>
        </dd>
    </dl>

    <?php $previous = $this->exception->getPrevious() ?>
    <?php while ($previous) : ?>
        <hr>

        <dl>
            <dt>Class</dt>
            <dd><?php echo get_class($previous) ?></dd>
            <dt>File</dt>
            <dd><?php echo $previous->getFile() ?>:<?php echo $previous->getLine() ?></dd>
            <dt>Message</dt>
            <dd><?php echo $previous->getMessage() ?></dd>
            <dt>Code</dt>
            <dd><?php echo $previous->getCode() ?></dd>
            <dt>Stack Trace</dt>
            <dd>
                <pre><?php echo $this->escapeHtml($previous->getTraceAsString()) ?></pre>
            </dd>
        </dl>

        <?php $previous = $previous->getPrevious() ?>
    <?php endwhile ?>
<?php endif ?>
